[phases.setup]
nixPkgs = ["nginx"]

[phases.build]
cmds = ["mkdir -p /usr/share/nginx/html", "cp index.html /usr/share/nginx/html/"]

[start]
cmd = "nginx -g 'daemon off;' -c /etc/nginx/nginx.conf"

[staticAssets]
path = "."
